### ISSUE TITLE
With large selections QGIS crashes when the mouse pointer hovers over the filter icon.

### ISSUE THREAD

**Issue by wvdbee** [caliskanmurat/qgis_create_layer_from_selected_features_plugin#1]
Whenever you hover the mouse pointer on top of the filter icon, QGIS shows the filterquery of the layer in a popup. If a  layer is generated with a lot of objects, i.e. the filter query contains al lot of ID's, QGIS is notable to show the filterquery in the popup: QGIS crashes.

I guess it's a limitation of QGIS. 

![afbeelding](https://user-images.githubusercontent.com/7975556/126044876-42c937a7-37ec-4762-ac4b-9e8f552aba82.png)

**Comment by wvdbee** [comment]
I've also filed an issue at the QGIS-project:
https://github.com/qgis/QGIS/issues/44217

**Comment by caliskanmurat** [comment]
Thank you very much for your feedback and interest. I think QGIS has a limit for filtering syntax. Besides the issue you mention, I also noticed that QGIS throws an error if the filtering syntax is too long.

**Comment by wvdbee** [comment]
About your remark on the size limitation of the filter query: any idea of the maximum size a selection can be?

**Comment by wvdbee** [comment]
QGIS issue 44217 has been closed with a solution. I guess this issue can be closed as well.
