### ISSUE TITLE
PostGis implementation

### ISSUE THREAD

**Issue by georgeportoferreira** [caliskanmurat/qgis_create_layer_from_selected_features_plugin#2]
Is there any work in progress to make it available on PostGis layers?
I'm experiencing the following error:
 CRITICAL    Layer streets_filtered : ERROR: column "fid" does not exist
             LINE 1: SELECT * FROM "schema"."streets" WHERE "fid" IN (954889...
              ^

**Comment by caliskanmurat** [comment]
Thank you for your warning. I will check and try to fix it.

**Comment by caliskanmurat** [comment]
PostGIS layers are available now. You can upgrade the plugin after approval.
If you encounter problems please inform me. Thank you for your interest.
